spring:
  application:
    name: jennifer.cubillas
  data:
    mongodb:
      uri: mongodb+srv://alecubillas31:Cubillas31@cluster0.q8n7w4f.mongodb.net/ia_db?appName=Cluster0
      database: ia_db
server:
  port: 8080

rapidapi:
  key: c7670db228msh4c0aee5e9a2ce22p14bf95jsndfd065182e43
  deep-translate:
    url: https://deep-translate1.p.rapidapi.com/language/translate/v2
    host: deep-translate1.p.rapidapi.com
  openai21:
    url: https://chatgpt-api8.p.rapidapi.com/
    host: chatgpt-api8.p.rapidapi.com
